import type { Metadata } from "next";
import { NavLinks } from '@/app/ui/nav-links';
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// 使用元数据 API<head> 修改 HTML 元素，例如 title 和 meta
export const metadata: Metadata = {
  title: "Babu",
  description: "Generated by create next app",
};

// 根布局
// 不应手动将诸如<title>和<meta>之类的<head>标签添加到根布局
// 元数据 API 可自动处理高级要求，例如流式传输和重复<head>元素删除
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavLinks list={list} />
        <main>{children}</main>
      </body>
    </html>
  );
}

const list = ['', 'dashboard', 'blog']